// UK lang variables
tinyMCE.addI18n('en.pastecode',{
paste_code_desc : _('Insert HTML code as text'),
paste_code_title : _('Use CTRL+V on your keyboard to paste the code into the window.'),
paste_html_desc : _('Paste HTML fragment (embed code)'),
paste_html_title : _('Use CTRL+V on your keyboard to paste the code into the window.'),
paste_math_title : _('Paste (CTRL+V) the code (LaTeX...) from your favorite editor or use eXeMathEditor'),
paste_include_wrapper : _('Include wrapper (improves presentation)'),
highlight_syntax : _('Highlight syntax'),
options : _('Options'),
language : _('Markup language'),
language_missing : _('Please select a language'),
not_defined : _('-- Not Set --'),
markup : _('Markup (HTML, etc.)'),
c_type : _('C type'),
presentation : _('Appearance'),
presentation_bright : _('Light'),
presentation_dark : _('Dark'),
line_numbers : _('Line numbers'),
line_highlight : _('Line highlight'),
example : _('Example'),
paste_math_desc : _('Paste mathematical markup'),
general : _('General'),
help : _('Help'),
use_code : _('Use code (recommended)'),
include_image : _('Include alternative image (recommended)'),
use_image : _('Use image'),
use_mathjax : _('Use MathJax from mathjax.org (online only) or your own copy'),
img_alt : _('Title (alternative text)'),
missing_alt:_("Continue without a title? Some users might see an image instead of the rendered code. Without the title the image may not be accessible to them."),
insert_code_without_image: _('The image could not be created. Insert the code without alternative image?'),
open_editor:_("Editor"),
equation_editor:_("Equation Editor"),
equation_editor_instructions:_("Click on the Editor's Save button when you finish editing."),
equation_editor_warning:_("You should save a copy of the code before continuing."),
// Errors
inline_popups_plugin_is_required : _('The plugin \u0022inlinepopups\u0022 must be enabled'),
jquery_is_required : _('jQuery is required')
});
